project:
  type: website
  output-dir: docs

website:
  title: "i9wa4's blog"
  site-url: "https://i9wa4.github.io/blog/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    left: "Built with [Quarto](https://quarto.org/)"
    center: "&copy;2024, i9wa4"
    right:
      - icon: github
        href: https://github.com/i9wa4
      - icon: x
        href: https://x.com/i9wa4_

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    toc-title: TOC
    toc-location: right

date-format: iso
