project:
  type: website
  output-dir: docs

website:
  title: "i9wa4's blog"
  site-url: "https://i9wa4.github.io/blog/"
  navbar:
    left:
      - href: "https://i9wa4.github.io/i9wa4"
        text: About
      - href: "https://i9wa4.github.io/blog"
        text: Blog
      - href: "https://i9wa4.github.io/slides"
        text: Slides
      - href: "https://i9wa4.github.io/resume"
        text: Resume
  page-footer:
    left: "Built with [Quarto](https://quarto.org/)"
    center: "&copy;2024, i9wa4"
    right:
      - icon: github
        href: https://github.com/i9wa4
      - icon: twitter-x
        href: https://x.com/i9wa4_

format:
  html:
    toc: true
    toc-depth: 2
    toc-title: TOC
    toc-location: right

lang: en
date-format: iso
theme: flatly
