project:
  type: website
  output-dir: "docs"

date-format: iso
theme:
  light: flatly
  dark: darkly

website:
  title: "i9wa4's blog"
  site-url: "https://i9wa4.github.io/blog/"
  favicon: "/assets/common/icon_hhkb2.jpg"
  image: "/assets/common/icon_hhkb2.jpg"
  search: true
  twitter-card:
    card-style: summary
    creator: "@i9wa4_"
    site: "@i9wa4_"
  open-graph: true
  navbar:
    left:
      - href: "https://i9wa4.github.io/i9wa4"
        text: "About"
      - href: "https://i9wa4.github.io/blog"
        text: "Posts"
      - href: "https://i9wa4.github.io/blog/slides"
        text: "Slides"
      - href: "https://i9wa4.github.io/resume"
        text: "Resume"
      - icon: github
        href: "https://github.com/i9wa4"
      - icon: twitter-x
        href: "https://x.com/i9wa4_"
  page-footer:
    left: "Built with [Quarto](https://quarto.org/)"
    center: "&copy;2024, i9wa4"
    right:
      - icon: github
        href: "https://github.com/i9wa4"
      - icon: twitter-x
        href: "https://x.com/i9wa4_"
      - icon: rss
        href: "index.xml"

format:
  html:
    toc: true
    toc-depth: 2
    toc-title: "TOC"
    toc-location: right
